name: CD
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: 0 0 * * *

jobs:
  setup-test:
    name: Setup ${{ matrix.buf }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [macos-latest, ubuntu-latest]
        buf: [0.36.0,0.35.1,0.34.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup-buf ${{ matrix.buf }}
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          buf-version: ${{ matrix.buf }}

      - name: verify buf
        run: tests/verify-buf.sh ${{ matrix.buf }}
        shell: bash
